### ISSUE TITLE
bacula-jobs / pgsql

### ISSUE THREAD

**Issue by FlorianHeigl** [Bastian-Kuhn/Check_MK-Treasures#1]
Hi Basti :-)

die meisten Bacula DBs laufen mit PostgreSQL.
Ich hab den Query angepasst

```
#!/bin/sh
echo "<<<bacula_jobs:sep(9)>>>"
echo "Select JobId, Name, JobStatus, EndTime FROM Job WHERE EndTime BETWEEN NOW() - interval '30 days' AND NOW();" | sudo -u postgres psql --tuples-only -AF $'\t'  bacula bacula
```

Was fehlt ist ne Auto-detection, ob MySQL oder PostgreSQL genutzt wird.
Es gibt ne Configdatei, in der der DB-Connect definiert wird, aber die Configs koennen includes, d.h. kaum zu schaffen, das per grep gut zu finden. Ich hab auch kein Kommando gefunden, um die config per bconsole anzuzeigen.

Was mein Vorschlag waere, als "gut genug"-Loesung:   

Per LDD nachschauen:

```
# ldd `which bacula-dir` | grep -i -e libmysqlclient -e libpq
	libpq.so.5 => /usr/local/lib/libpq.so.5 (0x803127000)
```

Waere das als Patch OK? Ich wuerd drei Faelle beachten:

1. MySQL gefunden (passender Query, ggf. passender sep())
2. PostgreSQL gefunden (passender Query, ggf. passender sep())
3. beides nicht gefunden (Plugin liefert dann einfach keine Daten)

evtl. gab es mal SQLite Support aber das war eh nicht fuer Prod und ich hab das noch niemals in echt gesehen.

Gruesse

**Comment by Bastian-Kuhn** [comment]
Hi Flo,

Sehr guter Punkt, danke schon mal.
Entweder wir machen es mit Erkennung, oder über eine Konfiguration die z.B. in der Agent Bakery gesetzt werden kann.

Die Automatische Erkennung wäre natürlich besser. Nur das wie gefällt mir noch nicht.
Gibt es hier ggf. eine Umgebungsvariable wie wir das rausbekomme? Woher weiss es z.B. das Programm selbst, sieht man es eventuell auch anhand eines Prozessparameters?

**Comment by robertoschwald** [comment]
Siehe PR #3

**Comment by Bastian-Kuhn** [comment]
@FlorianHeigl 

Kannst du das von Robert kurz testen? Habe selbst nicht die möglichkeit.

**Comment by gratuxri** [comment]
Postgresql query:
Select JobId, Name, JobStatus, EndTime FROM Job WHERE EndTime BETWEEN CURRENT_DATE - 30 and CURRENT_DATE ;

**Comment by robertoschwald** [comment]
See my new pull requests. With it, you can configure your db backend params in wato.
