### ISSUE TITLE
KVM/ QEMU Monitoring update for 1.6

### ISSUE THREAD

**Issue by ohobby** [Bastian-Kuhn/Check_MK-Treasures#10]
Hallo Bastian,
die aktuelle KVM/ QEMU Monitoring Version lässt sich nicht auf 1.6 installieren.
Ich bin noch nicht durch die ganzen Änderungen durchgestiegen um die Paketteile selbst anzupassen. 
Vielleicht könntest Du ja mal drüber schauen.

Danke und Grüße,
Oliver

**Comment by Bastian-Kuhn** [comment]
Hallo Oliver,

teste bitte teste jetzt noch mal mit der neusten Version.
Eigentlich war nur der Bakery Pfad Falsch, cool wenn der installer das bemerkt hat durch check der Versions nummer in der Info. Version 2 brauchst du
