### ISSUE TITLE
wrong data on centos8 while running plugin

### ISSUE THREAD

**Issue by doets001** [Bastian-Kuhn/Check_MK-Treasures#11]
A small issue when running the plugin. Maybe the behavior is not the same on every linux distribution. In the script you do a ps to get the PID of a vm, but it also returns the PID of the grep self. So the script is failing with wrong aguments.
A simple fix is to add a grep -v grep.

Change
PID=$(ps aux | grep kvm | grep $NAME | awk '{print $2}')
Into
PID=$(ps aux | grep kvm | grep $NAME | grep -v grep | awk '{print $2}')

-----
Error message on the orinal qemu plugin: 

<<<qemu>>>
./qemu: line 27: [: too many arguments
7 kvmcoreos03 running 4096
./qemu: line 27: [: too many arguments
8 kvmcoreos02 running 4096
./qemu: line 27: [: too many arguments
10 kvmcoreos01 running 4096

After the extra grep -v grep:
<<<qemu>>>
7 kvmcoreos03 running 4096 0.0 26.3
8 kvmcoreos02 running 4096 0.0 24.8
10 kvmcoreos01 running 4096 0.0 26.3

**Comment by Bastian-Kuhn** [comment]
Hi, 

I just updated the repo, Can you please test.

**Comment by Bastian-Kuhn** [comment]
And please, next time, name the Plugin in the title :)

**Comment by doets001** [comment]
Thnx! And the next time I will mention the plugin name :-). 
The plugin script is ok now. But I can't install the mkp file. Am I doing it wrong? I installed other mkp files in the same way.

**$ mkp install  qemu-2.0.mkp**
Traceback (most recent call last):
  File "/omd/sites/cmk/bin/check_mk", line 94, in <module>
    exit_status = modes.call(mode_name, mode_args, opts, args)
  File "/omd/sites/cmk/lib/python/cmk_base/modes/__init__.py", line 72, in call
    return mode.handler_function(*handler_args)
  File "/omd/sites/cmk/lib/python/cmk_base/modes/check_mk.py", line 626, in mode_packaging
    cmk_base.packaging.do_packaging(*args)
  File "/omd/sites/cmk/lib/python/cmk_base/packaging.py", line 185, in do_packaging
    f(args)
  File "/omd/sites/cmk/lib/python/cmk_base/packaging.py", line 513, in package_install
    return install_package(file_name=path)
  File "/omd/sites/cmk/lib/python/cmk_base/packaging.py", line 517, in install_package
    tar = tarfile.open(name=file_name, fileobj=file_object, mode="r:gz")
  File "/omd/sites/cmk/lib/python2.7/tarfile.py", line 1693, in open
    return func(name, filemode, fileobj, **kwargs)
  File "/omd/sites/cmk/lib/python2.7/tarfile.py", line 1751, in gzopen
    raise ReadError("not a gzip file")
tarfile.ReadError: not a gzip file

**$ mkp show  qemu-2.0.mkp**
Cannot open package qemu-2.0.mkp: not a gzip file

**$ omd sites**
SITE             VERSION          COMMENTS
cmk              1.6.0p6.cre      default version

**Comment by Bastian-Kuhn** [comment]
Hi, ich checked the file, I think something went wrong while downloading. 
Please try again :)

**Comment by doets001** [comment]
Yes, sorry, you where right. I downloaded it again, and now on the right way. 
Thnx!
