### ISSUE TITLE
postgres_replication

### ISSUE THREAD

**Issue by borissenkobogdan** [Bastian-Kuhn/Check_MK-Treasures#13]
Thank you very much for the wonderful plugin (postgres_replication).
I am trying to configure check_mk raw (edition) 16.0.p11 (centos8) on the server, 
the check_mk raw (edition) 16.0.p11 client (SLES12 postgres10), for some reason pnp4nagios does not draw graphics, 
therefore it does not work Critical and Warning Max Size. 
Can you know what could be the problem?

**Comment by Bastian-Kuhn** [comment]
Hello Boris,

sorry the Plugin Parts looks fine, so you need Debug on your Server (like is perfdata returned, is a rrd written?

**Comment by borissenkobogdan** [comment]
Hi Bastian-Kuhn
Yes, he writes, but nothing, it doesn’t display. I specifically generated a large data insertion and delayed data transfer to the replica, the graphs are silent, I checked the postgres_replication.sh script completely working.
I placed the postgres_replication.sh script in the agent directory / usr / lib / check_mk_agent / plugins
Granted the rights to chmod 755, and nothing more.
Maybe I forgot something?
In / Log check_mk nothing is written with an error, therefore I can not do debug.
----
Script output
----
psql (PostgreSQL) 10.11
<<<postgres_replication>>>
pg_slot_1 physical 12/A07C9CD8 1492082680 f 1423 MB
----
![изображение](https://user-images.githubusercontent.com/32158560/82319635-93370c00-99da-11ea-986c-f9b167e016d8.png)

**Comment by borissenkobogdan** [comment]
Many Thanks Bastian-Kuhn.
After update Check_MK to version 1.6.0.p14,  all the got work graphics.
