### ISSUE TITLE
VM piggyback  

### ISSUE THREAD

**Issue by wernermarcel1** [Bastian-Kuhn/Check_MK-Treasures#2]
Hallo Bastian, 

wäre es möglich den Check noch durch piggyback  Daten anzureichern ? 
Sodass die Info's ähnlich dem ESX Check angezeigt werden könnten ?

**Comment by Bastian-Kuhn** [comment]
Hallo Werner,

Grundsätzlich geht das bei vielen Checks wenn diese sinnvolle Daten auslesen.
Welche Check meinst du konkret?

**Comment by wernermarcel1** [comment]
Oh mann den Check vergessen.... 
Ich meine den KVM/Qemu check es wäre gut wenn die Daten ähnlich dem ESX Check auch in das HostObject mit gegeben werden also konkret : 

AgentAusgabe: 

2 hostname.host.local  running 32768 0.0 10.8
CPU: XX%, Memory: (assined: 32768 MB, used: XX%)

Dann im HostObject als 

KVM-CPU CPU: XX% 
KVM-MEM Memory: (assined: 32768 MB, used: XX%)

**Comment by Bastian-Kuhn** [comment]
Hallo Werner,

bitte teste mal meine änderung die du in Pull Request #4 findest. 
Wenn der funktioniert überlege ich mir wie ich das am besten einbaue.
