### ISSUE TITLE
mysql.status plugin WATO configuration

### ISSUE THREAD

**Issue by m3rlinux** [Bastian-Kuhn/Check_MK-Treasures#21]
Hi Bastian,
is there a way to specify a variable to catch (eg. "read_only") via WATO?

I managed to catch some variables by putting them into your plugin mysql.status:

```
...
"read_only"                         : ("Boolean", False),
...
```
Thanks!

**Comment by Bastian-Kuhn** [comment]
Hi, 

I'm sorry, but the discovery relays on the hardcoded values in the agent.
If you think they make sense, you can create a Pull Request and I will add them.
To make it flexible, we would need to create a Discovery Rule like e.g. the Interface Checks have them.
