### ISSUE TITLE
Exception: name perfometer_logarithmic is not defined in aborted_clients plugin of mysql_performance check

### ISSUE THREAD

**Issue by MArcNeuhaus** [Bastian-Kuhn/Check_MK-Treasures#24]
Hello,

we have an "Exception: name perfometer_logarithmic is not defined" in aborted_clients plugin for Perf-O-Meter of mysql_status check

Downloaded mkp from exchange.checkmk.com (v3.0.0)

Any knowledge on your side about this Problem?

**Comment by MArcNeuhaus** [comment]
After inserting an `from cmk.gui.plugins.views.perfometers import (
    perfometers,
    render_perfometer,
    perfometer_linear,
    perfometer_logarithmic,
    perfometer_logarithmic_dual,
    perfometer_logarithmic_dual_independent,
)`
in 
`mysql_status.py` the ErrorMSG is gone.

Don't know if it is the correct way to solve it.

**Comment by MArcNeuhaus** [comment]
diff --git a/mysql_status/src/web/plugins/perfometer/mysql_status.py b/mysql_status/src/web/plugins/perfometer/mysql_status.py
index 965db04..337dbc2 100644
--- a/mysql_status/src/web/plugins/perfometer/mysql_status.py
+++ b/mysql_status/src/web/plugins/perfometer/mysql_status.py
@@ -30,15 +30,6 @@

 # Perf-O-Meter for mysql_status

-from cmk.gui.plugins.views.perfometers import (
-    perfometers,
-    render_perfometer,
-    perfometer_linear,
-    perfometer_logarithmic,
-    perfometer_logarithmic_dual,
-    perfometer_logarithmic_dual_independent,
-)
-
 def perfometer_mysql_status(row, check_command, perf_data):
     color = { 0: "#a4f", 1: "#ff2", 2: "#f22", 3: "#fa2" }[row["service_state"]]
     return "%d" % int(perf_data[0][1]), perfometer_logarithmic(perf_data[0][1], 400, 2, color)

**Comment by halo779** [comment]
@MArcNeuhaus That looks to be it. Your Diff is a little backwards though.

It looks like at some stage they must have changed how the plugins work and force a little extra.
Need to check if all of those includes are actually required though.


Are you going to do a PR for it? Otherwise i'll add one, hopefully @Bastian-Kuhn can merge it in and update check_mk exchange

**Comment by Bastian-Kuhn** [comment]
Of course, I will merge and update the Checkmk Exchange. Already updated some plugins there, but takes ages for them to appear.

**Comment by Bastian-Kuhn** [comment]
@MArcNeuhaus can you open a Pull request for that? I will add it and update in on the Exchange

**Comment by MArcNeuhaus** [comment]
Sorry for the late reply. I was on vacation. Unfortunately I don't have the rights to push a branch. So I guess you better do it.

**Comment by Bastian-Kuhn** [comment]
Don't worry, you just need to Fork the Project, create a Branch, Change the code, commit, push, and then you can create a Pull request. So, it's certain that what is changed, is also tested since I can't test here.  And it will appear with your Name.

**Comment by Bastian-Kuhn** [comment]
Fix merged, many thank @MArcNeuhaus
