### ISSUE TITLE
pure needs purestorage python module

### ISSUE THREAD

**Issue by mfaust78** [Bastian-Kuhn/Check_MK-Treasures#40]
Just installed the pure CheckMK module and it didn't work.
Took me a while to realize that the "Pure Storage FlashArray REST Client" is needed for it to work.
https://pypi.org/project/purestorage/
installed it via 
_pip3 install purestorage_ 
works now.
Might be good to add that to the documentation (or automate the install if possible).

**Comment by Bastian-Kuhn** [comment]
Thank you very much, yes that's true.
I added it to the Documentation. Automated install I would not want, since this is not possible in all environments and also a possible security risk.
