### ISSUE TITLE
mysql_status multiple instances

### ISSUE THREAD

**Issue by m3rlinux** [Bastian-Kuhn/Check_MK-Treasures#8]
Hi Bastian,
unfortunately your plugin doesn't support multiple instances of Mysql on the same server.
Do you think to implement this feature?
I am trying to figure it out but it's very hard for me becouse my poor python knowledge.

Many thanks!

**Comment by Bastian-Kuhn** [comment]
Hi,

sadly don't have the free time to do so, but maybe another on-site Customer needs it, then I can fix it there.

**Comment by Bastian-Kuhn** [comment]
Ok, maybe you have look. The Check will get 1.6 support, and therefore also instances :)

**Comment by Bastian-Kuhn** [comment]
@m3rlinux 
Please Check version 3 of the MKP, there should be support now for instances

**Comment by m3rlinux** [comment]
Excellent! Many, many thanks!
FYI... becouse it isn't possible to install the package on check_mk 1.5 I overwrite only the check and it works like a charm!
God Job man!

**Comment by Bastian-Kuhn** [comment]
Oh, if it is working on 1.5, i will change the min_version to 1.5. Used 1.6 Check API stuff at first, but removed it then
