### ISSUE TITLE
How to use max_age?

### ISSUE THREAD

**Issue by garnser** [Bastian-Kuhn/Check_MK-Treasures#9]
Hi and thanks for this great plugins.

I'm trying to get an understanding of how to use the max_age parameter available in bacula_jobs. What's the expected input to utilize this? I'd would like to compare if the backups is greater than X hours or days, is this possible?

Thanks

**Comment by Bastian-Kuhn** [comment]
Just set it up in WATO, there you can use every age you want.
Is then saved as seconds into the configuration.
